development:
  adapter: mysql2
  encoding: utf8
  database: easy_gift_dev
  username: root
  password:
  host: 127.0.0.1
  port: 3306

# development:
#   adapter: postgresql
#   encoding: unicode
#   database: easy_gift_dev
#   host: localhost

# test:
#   adapter: postgresql
#   encoding: unicode
#   database: easy_gift_test
#   host: localhost

# production:
#   adapter: postgresql
#   encoding: unicode
#   database: easy_gift_production